#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build immortalwrt24.10-6.6 JCG Q30Pro Latest Passwall

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: openwrt-24.10-6.6
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 2410-6.6-q30pro-openclash.config
  DIY_P1_SH: 2410-diy-part1-pw.sh
  DIY_P2_SH: 2410-6.6-diy-part2-6-1-pw.sh
  RELEASE_FILE: 2410-6.6-oh-release.txt  
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        
        # 积极清理不必要的文件以释放磁盘空间
        echo "Aggressively cleaning up unnecessary files to free disk space..."
        sudo apt-get -qq autoremove --purge
        sudo apt-get -qq clean
        sudo rm -rf /usr/share/doc/*
        sudo rm -rf /usr/share/man/*
        sudo rm -rf /usr/share/locale/*
        sudo rm -rf /var/cache/apt/archives/*.deb
        sudo rm -rf /var/lib/apt/lists/*
        sudo rm -rf /tmp/*
        sudo rm -rf /var/tmp/*
        
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
        echo "Disk space after initialization and aggressive cleanup:"
        df -hT # 检查清理后的磁盘空间

    # --- 禁用 ccache 缓存 ---
    # - name: Setup ccache
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.ccache
    #     key: ccache-${{ runner.os }}-${{ env.REPO_BRANCH }}-${{ hashFiles(env.CONFIG_FILE) }}
    #     restore-keys: |
    #       ccache-${{ runner.os }}-${{ env.REPO_BRANCH }}-
    #     enableCrossOsArchive: true

    # - name: Enable ccache
    #   run: |
    #     echo "USE_CCACHE=1" >> $GITHUB_ENV
    #     echo "CCACHE_DIR=~/.ccache" >> $GITHUB_ENV
    #     ccache -M 10G
    #     ccache -z
    # --- 禁用 ccache 缓存结束 ---

    - name: Clone source code
      working-directory: /workdir
      run: |
        echo "Disk space before cloning source code:"
        df -hT $PWD
        echo "Performing a shallow clone to save space..."
        git clone --depth=1 --single-branch -b $REPO_BRANCH $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        echo "Disk space after shallow clone:"
        df -hT $PWD
        echo "Size of the .git directory:"
        du -sh /workdir/openwrt/.git

    # --- 禁用 DL 缓存 ---
    # - name: Restore DL cache
    #   uses: actions/cache@v4
    #   with:
    #     path: openwrt/dl
    #     key: dl-${{ runner.os }}-${{ env.REPO_BRANCH }}-${{ hashFiles(env.CONFIG_FILE) }}
    #     restore-keys: |
    #       dl-${{ runner.os }}-${{ env.REPO_BRANCH }}-
    #     enableCrossOsArchive: true
    # --- 禁用 DL 缓存结束 ---

    - name: Load custom feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      run: |
         cd openwrt
         ./scripts/feeds update -a
         rm -rf feeds/packages/lang/golang
         git clone https://github.com/kenzok8/golang feeds/packages/lang/golang

    - name: Install feeds
      run: |
        cd openwrt
        ./scripts/feeds install -a 
        
    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        
        # Download and apply the custom filogic.mk
        echo "Downloading custom filogic.mk for JCG Q30 Pro factory support..."
        wget -q https://raw.githubusercontent.com/huniangitb/ideal-pancake/refs/heads/main/filogic.mk -O openwrt/target/linux/mediatek/image/filogic.mk
        
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Prepare configuration and download packages
      id: package
      run: |
        cd openwrt
        make oldconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        echo "Disk space after package download (dl directory):"
        df -h # 检查下载包后的磁盘空间

        
    - name: Generate artifact information
      run: |
        cd openwrt
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
    - name: Prepare build configuration for upload
      run: |
        echo "Verifying .config file existence:"
        ls -la openwrt/.config
        echo "Copying .config to build.config for artifact upload."
        cp openwrt/.config openwrt/build.config

    - name: Upload build configuration
      uses: actions/upload-artifact@v4.6.2
      with:
        name: build-config${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/build.config

    - name: Clean build directories
      run: |
        cd openwrt
        # "make clean" is commented out to speed up rebuilds on failure.
        # make clean

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s || make -j1 V=sc # 增加 V=s/V=sc 用于调试
        echo "status=success" >> $GITHUB_OUTPUT
        echo "Disk space after compilation:"
        df -h

    # --- 禁用 ccache 统计 ---
    # - name: Show ccache statistics
    #   if: (!cancelled())
    #   run: |
    #     ccache -s
    # --- 禁用 ccache 统计结束 ---

    - name: Check space usage (Final check)
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@v4.6.2
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@v4.6.2
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch "${RELEASE_FILE}"
        echo "status=success" >> $GITHUB_OUTPUT
    
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2.3.2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: ${{ env.RELEASE_FILE }}
        files: ${{ env.FIRMWARE }}/*

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2.0.6
      with:
        retain_days: 0
        keep_minimum_runs: 2
        
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 12
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
